apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ybjf0lv7k-python 
  janus-idp.io/tekton: ybjf0lv7k-python
  backstage.io/kubernetes-id: ybjf0lv7k-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ybjf0lv7k-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml